### ISSUE TITLE
Updated CMOR driver for COSP2

### ISSUE THREAD

**Issue by dustinswales** [CFMIP/COSPv2.0#8]
@alejandrobodas 
@RobertPincus 

I'm not sure how important this is, especially that we now have a non-CMOR dependent offline driver, but is there a desire to update the CMOR driver to use the latest version of CMOR (version3)? 

Dustin

**Comment by RobertPincus** [comment]
Dustin, did we not have  recent user complaint about trying to build the CMOR driver with a version of CMOR that’s no longer supported and not used by CMIP?

@alejandrobodas<https://github.com/alejandrobodas>
@RobertPincus<https://github.com/robertpincus>

I'm not sure how important this is, especially that we now have a non-CMOR dependent offline driver, but is there a desire to update the CMOR driver to use the latest version of CMOR (version3)?

Dustin

**Comment by dustinswales** [comment]
Robert,
Yes we did (https://groups.google.com/forum/#!topic/cosp-user/42VrqM87Y7w)

**Comment by klein21** [comment]
Dustin,

If we remove the CMOR capability from the test program, do we lose anything capability/functionality?

Do climate models build their own interfaces to CMOR, such that climate models don’t directly use whatever CMOR interface is in the COSP testing program?

If so, the only people harmed by removing CMOR from the COSP testing program would be those that run COSP offline, but also want to submit the offline calculated values to CMIP/CFMIP.  However, I don’t believe there are any such users as all COSP use within CMIP/CFMIP is done inline.

If so, it would be good to remove the CMOR interface, because it is not needed and because it causes trouble with those who want to test COSP but don’t need CMOR.   Being decoupled from the CMOR developments is another plus in my mind.

As for the rest of the reorganization of the code, I don’t have a specific comment, other than to confirm with you that the changes do not alter (significantly) the test program’s output.

Steve

**Comment by RobertPincus** [comment]
> As for the rest of the reorganization of the code, I don’t have a specific comment, other than to confirm with you that the changes do not alter (significantly) the test program’s output. 

Steve - 

The merge proposed by Dustin includes no changes to source code at all beyond adding the new non-CMOR driver. Thus any changes you see should be entirely the result of using different compilers, etc. Does that seem consistent with what you’re seeing? 

Alejandro was advocating for CMOR support most vocally. I’ll be interested to hear what he has to say. 

- Robert

**Comment by klein21** [comment]
Robert,

I haven’t looked at the output. I agree with you that there shouldn’t be any significant changes because there are no changes to the source code beyond the driver. I am asking Dustin to confirm that this is case.

Yes, I am curious to know what Alejandro thinks. His opinion should carry more weight given that he has much more knowledge about the underlying code and relevant issues than do I.

Steve

**Comment by RobertPincus** [comment]
Ah - you’re asking if the answers have changed for us. They have not. 

- Robert

**Comment by klein21** [comment]
Thanks!

**Comment by alejandrobodas** [comment]
@dustinswales @RobertPincus @klein21 Hi, I am in favour of deleting the CMOR interface. This interface was used for CMIP5, when one or two modelling centres run COSP offline. I don't think this is needed any more, and it makes the installation overly complex due to a number of additional external dependencies. Perhaps we could ask in the cosp-users group, just to be sure than no-one is opposed to this.
However, I think the netcdf output should be CF-compliant so that it can still be easily readable by many data analysis software. In principle, this should not be too difficult.

**Comment by RobertPincus** [comment]
@alejandrobodas I’m all in favor of dropping CMOR support too, for the reasons you mention. I have been finding strict CF compliance a little difficult to achieve with RFMIP files. Given that the main role of this offline driver is to flag code changes that affect answers, how much effort do you think we should devote to this?


@dustinswales<https://github.com/dustinswales> @RobertPincus<https://github.com/robertpincus> @klein21<https://github.com/klein21> Hi, I am in favour of deleting the CMOR interface. This interface was used for CMIP5, when one or two modelling centres run COSP offline. I don't think this is needed any more, and it makes the installation overly complex due to a number of additional external dependencies. Perhaps we could ask in the cosp-users group, just to be sure than no-one is opposed to this.
However, I think the netcdf output should be CF-compliant so that it can still be easily readable by many data analysis software. In principle, this should not be too difficult.

**Comment by alejandrobodas** [comment]
@RobertPincus That's why I think doing a quick survey among the users would be good. If the offline use is very small or non-exsitent, then making the files CF-compliant would not be that important.
@dustinswales Is there an output file already available in the repository? I could run it through a CF checker and see if the issues are major ones or not.

**Comment by RobertPincus** [comment]
@alejandrobodasThe example output file is in driver/data/outputs/UKMO/cosp2_output_um.ref.nc .

**Comment by alejandrobodas** [comment]
@RobertPincus thanks for this. I think the file is nearly a minimalist CF-compliant file. I have a few suggestions that I think should be easy to add:

1) add a variable for each of the dimensions. For instance, when I read the MISR histogram, I get
 MISR CFAD / (%) (altitude_bin_centers: 16; cloud_optical_depth_bin_centers: 7; -- : 153)

but when I read in the 3D calipso cloud fraction I get:

Calipso cloud-fraction / (%) (-- : 40; -- : 153)

The '--' indicates that there is no variable associated with that axis. Hopefully adding these is not too much work.

2) The CF checker complains of the following:
latitude variable 'latitude' should define standard_name='latitude'
(same for longitude)

Global attribute 'Conventions' field is not present

3) Whenever possible, I would add the standard_name attribute.

4) Some of the long names are not strictly correct, e.g. use of 'CFAD' for ISCCP and MISR histograms.

**Comment by klein21** [comment]
Robert or Dustin,

I like Alejandro’s idea for sending a quick message out to the COSP-user maillist, asking if anybody would miss deleting the CMOR interface from the COSP2 testing program. You might learning something relevant.

Steve

**Comment by RobertPincus** [comment]
I did this already this morning. You didn’t get it? 

- R

**Comment by klein21** [comment]
No I didn’t, but I have noticed recently that delivery into my LLNL inbox of e-mail from Google groups has been slow…. I don’t know what that’s about…

**Comment by klein21** [comment]
Oh, I think the problem may be with the e-mail address I associate with Google. Anyways, I see your message Robert to the COSP-user group….

From: "Klein, Stephen A." <klein21@llnl.gov>
Date: Wednesday, March 14, 2018 at 9:30 AM
To: "CFMIP/COSPv2.0" <reply@reply.github.com>, "CFMIP/COSPv2.0" <COSPv2.0@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [CFMIP/COSPv2.0] Updated CMOR driver for COSP2 (#8)

No I didn’t, but I have noticed recently that delivery into my LLNL inbox of e-mail from Google groups has been slow…. I don’t know what that’s about…

**Comment by dustinswales** [comment]
CMOR capability has been removed from COSP2 offline driver.
